# Generated by Django 5.0 on 2025-03-08 03:27

import authentication.models
import django.core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="This field must start with a letter and contain only alphanumeric characters.",
                                regex="^[a-zA-Z][a-zA-Z0-9]*$",
                            ),
                            django.core.validators.MinLengthValidator(6),
                            django.core.validators.MaxLengthValidator(30),
                        ],
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        default="",
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid email value",
                                regex="^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$",
                            )
                        ],
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="First name can only contain alphabetic characters.",
                                regex="^[a-zA-Z]+$",
                            ),
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.MaxLengthValidator(20),
                        ],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Last name can only contain alphabetic characters.",
                                regex="^[a-zA-Z]+$",
                            ),
                            django.core.validators.MinLengthValidator(2),
                            django.core.validators.MaxLengthValidator(20),
                        ],
                    ),
                ),
                ("password", models.CharField(blank=True, null=True)),
                (
                    "picture",
                    models.CharField(
                        default="https://avatar.iran.liara.run/public",
                        max_length=255,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=8, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("two_factor_enabled", models.BooleanField(default=False)),
                ("otp_base32", models.CharField(blank=True, max_length=200, null=True)),
                ("otp_url", models.CharField(blank=True, max_length=255, null=True)),
                ("username_last_updated", models.DateField(blank=True, null=True)),
                ("picture_last_updated", models.DateField(blank=True, null=True)),
                ("password_last_updated", models.DateField(blank=True, null=True)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("email_verified", models.BooleanField(default=False)),
                ("is_online", models.BooleanField(default=False)),
                ("active_sessions", models.IntegerField(default=0)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("games_played", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
            managers=[
                ("objects", authentication.models.CustomUserManager()),
            ],
        ),
    ]
