# Generated by Django 5.0 on 2025-03-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="picture",
            field=models.CharField(default="/default_profile.png", max_length=255),
        ),
    ]
