# Generated by Django 5.0 on 2025-03-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_alter_user_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="total_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="wins",
            field=models.IntegerField(default=0),
        ),
    ]
