# Generated by Django 5.0 on 2025-03-11 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_user_total_score_user_wins"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="total_score",
        ),
        migrations.RemoveField(
            model_name="user",
            name="wins",
        ),
    ]
