# Generated by Django 5.0 on 2025-03-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_remove_user_total_score_remove_user_wins"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="total_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="wins",
            field=models.IntegerField(default=0),
        ),
    ]
