# Generated by Django 5.0 on 2025-03-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_user_total_score_user_wins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="total_score",
            field=models.IntegerField(default=1000),
        ),
    ]
