# Generated by Django 5.0 on 2025-03-14 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tictactoe", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tictactoematch",
            old_name="played_at",
            new_name="created_at",
        ),
    ]
