# Generated by Django 5.0 on 2025-03-15 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tictactoe", "0002_rename_played_at_tictactoematch_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tictactoematch",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "TicTacToe Match",
                "verbose_name_plural": "TicTacToe Matches",
            },
        ),
        migrations.CreateModel(
            name="TicTacToePlayerStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("games_played", models.IntegerField(default=0)),
                ("wins", models.IntegerField(default=0)),
                ("draws", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tictactoe_stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "TicTacToe Player Stats",
                "verbose_name_plural": "TicTacToe Player Stats",
            },
        ),
    ]
