# Generated by Django 5.0 on 2025-03-21 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tictactoe", "0003_alter_tictactoematch_options_tictactoeplayerstats"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="tictactoematch",
            name="winner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tictactoe_winner",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
