# Generated by Django 5.0 on 2025-03-22 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tictactoe", "0004_alter_tictactoematch_winner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tictactoematch",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="tictactoeplayerstats",
            options={},
        ),
    ]
