# Generated by Django 5.0 on 2025-03-08 03:27

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TournamentTheme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(default="", max_length=255, null=True)),
                (
                    "description1",
                    models.CharField(default="", max_length=1024, null=True),
                ),
                (
                    "description2",
                    models.CharField(default="", max_length=1024, null=True),
                ),
                ("color1", models.CharField(default="", max_length=10, null=True)),
                ("color2", models.CharField(default="", max_length=10, null=True)),
                ("color3", models.CharField(default="", max_length=10, null=True)),
                ("color4", models.CharField(default="", max_length=10, null=True)),
                (
                    "picture1",
                    models.CharField(
                        default="https://avatar.iran.liara.run/public",
                        max_length=255,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "picture2",
                    models.CharField(
                        default="https://avatar.iran.liara.run/public",
                        max_length=255,
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
            ],
            options={
                "verbose_name": "TournamentTheme",
            },
        ),
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
                ("game", models.CharField(default="", max_length=30)),
                ("participants", models.IntegerField(default=0)),
                ("opened", models.DateTimeField(auto_now_add=True, null=True)),
                ("started", models.CharField(default="", max_length=255)),
                ("closed", models.CharField(default="", max_length=255)),
                ("is_open", models.BooleanField(default=True)),
                ("is_full", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "players",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theme",
                        to="tournament.tournamenttheme",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tournament",
            },
        ),
    ]
