# Generated by Django 5.0 on 2025-03-10 22:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tournamenttheme",
            name="picture1",
            field=models.CharField(
                default="/default_profile.png",
                max_length=255,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="tournamenttheme",
            name="picture2",
            field=models.CharField(
                default="/default_profile.png",
                max_length=255,
                validators=[django.core.validators.URLValidator()],
            ),
        ),
    ]
