# Generated by Django 5.0 on 2025-03-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0003_tournament_fina_winner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tournament",
            old_name="fina_winner",
            new_name="final_winner",
        ),
    ]
