# Generated by Django 5.0 on 2025-03-21 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0004_rename_fina_winner_tournament_final_winner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tournament",
            name="theme",
        ),
        migrations.DeleteModel(
            name="TournamentTheme",
        ),
    ]
