# Generated by Django 5.0 on 2025-03-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="loser_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="match",
            name="winner_score",
            field=models.IntegerField(default=0),
        ),
    ]
